language: node_js
node_js:
  - "6"
notifications:
  email:
    recipients:
      - ricardogcolombo@gmail.com
      - samuelfabrizio@gmail.com
      - alan.campora@gmail.com
    on_success: [change]
    on_failure: [always]
